version: "3"
services:
  react:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
