# Generated by Django 3.2.9 on 2021-12-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('accounts', '0003_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounts.account', verbose_name='account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('coin', 'account')},
        ),
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
    ]
