# Generated by Django 3.2.9 on 2021-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211206_1231'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
    ]
