# Generated by Django 3.2.9 on 2021-12-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_balance_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['account', 'coin'], 'verbose_name': 'balance', 'verbose_name_plural': 'balances'},
        ),
    ]
